name = "vpn"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "81dbb6b2-bd76-442e-8a39-35bfe340a802"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
